# Generated by Django 3.2.5 on 2021-08-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(to='pizzaApp.Pizza'),
        ),
    ]
